"""UI text localization for the Lottery Statistics Dashboard."""

from __future__ import annotations

DEFAULT_LANGUAGE = "th"
LANGUAGE_OPTIONS = ["th", "en"]
LANGUAGE_LABELS = {
    "th": "ไทย",
    "en": "English",
}

TEXT = {
    "th": {
        "app_title": "แดชบอร์ดวิเคราะห์สถิติลอตเตอรี่",
        "safety_note": "เป็นการวิเคราะห์สถิติย้อนหลังเท่านั้น ไม่ใช่การทำนายหรือการการันตีผล",
        "login": "เข้าสู่ระบบ",
        "logout": "ออกจากระบบ",
        "logged_in": "เข้าสู่ระบบแล้ว",
        "username": "ชื่อผู้ใช้",
        "password": "รหัสผ่าน",
        "missing_login_config": "Missing login config",
        "invalid_login": "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
        "language": "ภาษา",
        "settings": "ตั้งค่า",
        "prediction_method": "วิธีวิเคราะห์",
        "rolling_span": "ช่วงข้อมูลย้อนหลัง",
        "top_n_suggestions": "จำนวนเลขแนะนำ",
        "all_prior_rows": "ข้อมูลก่อนหน้าทั้งหมด",
        "rows": "งวด",
        "tab_history": "ประวัติผลย้อนหลัง",
        "tab_add": "เพิ่มผลงวดใหม่",
        "tab_next": "วิเคราะห์งวดถัดไป",
        "tab_prediction_history": "ประวัติเลขแนะนำ",
        "tab_accuracy": "ความแม่นยำย้อนหลัง",
        "tab_insights": "อินไซต์จากสถิติ",
        "tab_status": "สถานะระบบ",
        "tab_backup": "สำรองข้อมูล / ส่งออก",
        "tab_model": "เปรียบเทียบโมเดล",
        "tab_backtest": "ทดสอบย้อนหลัง",
        "tab_summary": "สรุปภาพรวม",
        "tab_digits": "ความถี่ตัวเลข",
        "tab_last2": "เลขท้าย 2 ตัวที่พบบ่อย",
        "tab_3digit": "เลข 3 ตัวที่พบบ่อย",
        "history_rows": "จำนวนข้อมูลงวด",
        "latest_draw": "งวดล่าสุด",
        "current_method": "วิธีที่เลือก",
        "last_updated": "อัปเดตล่าสุด",
        "add_new_result": "เพิ่มผลงวดใหม่",
        "save_result": "บันทึกผล",
        "next_draw_analysis": "วิเคราะห์งวดถัดไป",
        "source_rows": "จำนวนข้อมูลที่ใช้",
        "frequency_last2_top": "เลขท้าย 2 ตัวตามความถี่ สูงสุด",
        "frequency_3digit_top": "เลข 3 ตัวตามความถี่ สูงสุด",
        "weighted_last2_top": "เลขท้าย 2 ตัวแบบถ่วงน้ำหนัก สูงสุด",
        "weighted_3digit_top": "เลข 3 ตัวแบบถ่วงน้ำหนัก สูงสุด",
        "hybrid_last2_top": "เลขท้าย 2 ตัวแบบ Hybrid สูงสุด",
        "hybrid_3digit_top": "เลข 3 ตัวแบบ Hybrid สูงสุด",
        "digit_position_analysis": "วิเคราะห์ตำแหน่งตัวเลข",
        "last2_positions": "ตำแหน่งเลขท้าย 2 ตัว",
        "three_digit_positions": "ตำแหน่งเลข 3 ตัว",
        "hot_cold_numbers": "เลขที่พบบ่อย / พบน้อย",
        "hot_last2": "เลขท้าย 2 ตัวที่พบบ่อย",
        "hot_3digit": "เลข 3 ตัวที่พบบ่อย",
        "cold_last2": "เลขท้าย 2 ตัวที่พบน้อย",
        "cold_3digit": "เลข 3 ตัวที่พบน้อย",
        "method": "method",
        "save_analysis": "บันทึกเลขแนะนำ",
        "prediction_history": "ประวัติเลขแนะนำ",
        "model_accuracy": "ความแม่นยำย้อนหลัง",
        "total_predictions": "จำนวนรายการเลขแนะนำ",
        "evaluated": "จำนวนที่ตรวจแล้ว",
        "hit_rate_percent": "อัตราเข้า %",
        "tracking_file": "ไฟล์ติดตามผล",
        "accuracy_table": "ตารางความแม่นยำ",
        "leaderboard_model_ranking": "อันดับโมเดล",
        "hit_rate_comparison": "เปรียบเทียบอัตราเข้า",
        "accuracy_trend": "แนวโน้มความแม่นยำย้อนหลัง",
        "accuracy_refreshed": "อัปเดตความแม่นยำย้อนหลังจากผลจริงที่มีแล้ว",
        "no_evaluated_predictions": "ยังไม่มีรายการเลขแนะนำที่ตรวจเทียบผลจริงแล้ว ให้บันทึกเลขแนะนำสำหรับงวด แล้วเพิ่มผลจริงเมื่อมีข้อมูล",
        "ai_insights": "อินไซต์จากสถิติ",
        "insight_caption": "Insight Layer ใช้การวิเคราะห์สถิติย้อนหลังแบบ deterministic เท่านั้น",
        "insight_cards": "การ์ดอินไซต์",
        "average_confidence": "ความเชื่อมั่นเฉลี่ย",
        "high_signals": "สัญญาณ HIGH",
        "generated": "สร้างเมื่อ",
        "warnings": "คำเตือน",
        "signal_confidence": "สัญญาณ / ความเชื่อมั่น",
        "warning": "คำเตือน",
        "insight_table": "ตารางอินไซต์",
        "digit_heatmap": "แผนภาพความถี่ตัวเลข",
        "trend_chart": "กราฟแนวโน้ม",
        "digit_movement_chart": "กราฟการเคลื่อนไหวของตัวเลข",
        "insight_history": "ประวัติอินไซต์",
        "no_insight_warnings": "ไม่พบคำเตือนสำคัญจากขนาดข้อมูลและการกระจายตัวปัจจุบัน",
        "system_status": "สถานะระบบ",
        "best_model": "โมเดลที่ดีที่สุด",
        "latest_accuracy": "ความแม่นยำล่าสุด",
        "latest_processed_draw": "งวดล่าสุดที่ประมวลผล",
        "system_last_refresh": "รีเฟรชระบบล่าสุด",
        "prediction_records": "จำนวนประวัติเลขแนะนำ",
        "data_quality": "คุณภาพข้อมูล",
        "not_evaluated": "ยังไม่ได้ประเมิน",
        "system_ready": "ระบบพร้อมใช้งาน เป็นการวิเคราะห์สถิติย้อนหลังเท่านั้น",
        "refresh_system_status": "รีเฟรชสถานะระบบ",
        "current_leaderboard": "อันดับโมเดลปัจจุบัน",
        "latest_process_log": "ประวัติการประมวลผลล่าสุด",
        "backup_export": "สำรองข้อมูล / ส่งออก",
        "backup_file_count": "จำนวนไฟล์สำรอง",
        "latest_export_time": "เวลาส่งออกล่าสุด",
        "storage_usage_estimate": "พื้นที่ใช้งานโดยประมาณ",
        "backup_retention": "นโยบายเก็บ backup",
        "latest_backup_table": "ตาราง backup ล่าสุด",
        "latest_count": "ล่าสุด",
        "no_backup_center_files": "ยังไม่มีไฟล์สำรองจาก Backup Center",
        "create_backup": "สร้างไฟล์สำรอง",
        "backup_history": "สำรองประวัติผล",
        "backup_accuracy": "สำรองความแม่นยำ",
        "backup_latest_prediction": "สำรองเลขแนะนำล่าสุด",
        "backup_system_log": "สำรอง log ระบบ",
        "export": "ส่งออก",
        "export_predictions_csv": "ส่งออกเลขแนะนำ CSV",
        "export_accuracy_csv": "ส่งออกความแม่นยำ CSV",
        "export_history_csv": "ส่งออกประวัติผล CSV",
        "export_full_system_zip": "ส่งออกทั้งระบบ ZIP",
        "download_latest_export": "ดาวน์โหลดไฟล์ส่งออกล่าสุด",
        "restore_safety": "ความปลอดภัยในการกู้คืน",
        "restore_caption": "การกู้คืนจะตรวจสอบโครงสร้าง CSV ก่อนแทนที่ไฟล์จริง",
        "no_restore_candidates": "ยังไม่มีไฟล์สำรองสำหรับกู้คืน",
        "backup_file": "ไฟล์สำรอง",
        "restore_target": "ไฟล์เป้าหมายสำหรับกู้คืน",
        "validate_backup": "ตรวจสอบไฟล์สำรอง",
        "restore_selected_backup": "กู้คืนไฟล์สำรองที่เลือก",
        "backup_valid": "โครงสร้างไฟล์สำรองถูกต้องสำหรับไฟล์เป้าหมายที่เลือก",
        "model_comparison": "เปรียบเทียบโมเดล",
        "rolling_accuracy_trend": "แนวโน้มความแม่นยำแบบ rolling",
        "backtest": "ทดสอบย้อนหลัง",
        "backtest_note": "การทดสอบย้อนหลังใช้เฉพาะข้อมูลก่อนงวดที่ทดสอบเท่านั้น",
        "run_backtest": "รันทดสอบย้อนหลัง",
        "summary": "สรุปภาพรวม",
        "recalculate_summary": "คำนวณสรุปใหม่",
        "digit_frequency": "ความถี่ตัวเลข",
        "top_last2": "เลขท้าย 2 ตัวที่พบบ่อย",
        "top_3digit": "เลข 3 ตัวที่พบบ่อย",
        "download": "ดาวน์โหลด",
        "refresh_completed": "รีเฟรชเสร็จแล้ว",
        "refresh_failed": "รีเฟรชไม่สำเร็จ",
        "backtest_failed": "ทดสอบย้อนหลังไม่สำเร็จ",
        "recalculate_failed": "คำนวณสรุปใหม่ไม่สำเร็จ",
        "auto_processing_completed": "ประมวลผลอัตโนมัติเสร็จแล้ว",
        "auto_processing_failed": "ประมวลผลอัตโนมัติไม่สำเร็จ ระบบจะย้อนกลับข้อมูลเมื่อทำได้",
        "analysis_saved_backup": "บันทึกเลขแนะนำแล้ว สร้างไฟล์สำรอง",
        "analysis_saved_tracking": "บันทึกเลขแนะนำแล้ว สร้างไฟล์ติดตามผลเรียบร้อย",
        "save_analysis_failed": "บันทึกเลขแนะนำไม่สำเร็จ",
        "backup_created": "สร้างไฟล์สำรองแล้ว",
        "best_current_model": "โมเดลที่ดีที่สุดจากการติดตามย้อนหลัง",
        "insight_history_updated": "อัปเดตประวัติอินไซต์แล้ว",
        "new_cards": "การ์ดใหม่",
        "insight_backup_created": "สร้างไฟล์สำรองก่อนเขียนทับประวัติอินไซต์",
        "status_needs_attention": "สถานะระบบต้องตรวจสอบ",
        "refreshing_system": "กำลังรีเฟรชสถิติ ความแม่นยำ อันดับโมเดล และเลขแนะนำล่าสุด...",
        "manual_backup_success": "สร้างไฟล์สำรองแล้ว",
        "manual_backup_failed": "สร้างไฟล์สำรองไม่สำเร็จ",
        "export_created": "สร้างไฟล์ส่งออกแล้ว",
        "export_failed": "ส่งออกไม่สำเร็จ",
        "full_export_created": "สร้างไฟล์ส่งออกทั้งระบบแล้ว",
        "full_export_failed": "ส่งออกทั้งระบบไม่สำเร็จ",
        "backup_validation_failed": "ตรวจสอบไฟล์สำรองไม่สำเร็จ",
        "restore_completed": "กู้คืนเสร็จแล้ว ไฟล์ปัจจุบันถูกสำรองไว้ก่อน",
        "restore_blocked": "หยุดการกู้คืน",
        "running_backtest": "กำลังรันทดสอบย้อนหลัง...",
        "last_result_file": "ไฟล์ผลลัพธ์ล่าสุด",
        "detail_csv": "ไฟล์รายละเอียด CSV",
        "recalculating_summary": "กำลังคำนวณสรุปใหม่...",
        "summary_recalculated": "คำนวณสรุปใหม่สำเร็จ",
        "backtest_completed": "ทดสอบย้อนหลังเสร็จแล้ว",
        "accuracy_leaderboard_refreshed": "อัปเดตความแม่นยำและอันดับโมเดลแล้ว",
        "prediction_history_refreshed": "อัปเดตประวัติเลขแนะนำแล้ว",
        "latest_prediction_generated": "สร้างเลขแนะนำล่าสุดแล้ว",
        "backtest_model_refreshed": "อัปเดตทดสอบย้อนหลังและเปรียบเทียบโมเดลแล้ว",
        "saved_result_backup": "บันทึกผลแล้ว สร้างไฟล์สำรอง",
        "missing_data_file": "ไม่พบไฟล์ข้อมูล",
        "missing_summary_file": "ไม่พบไฟล์สรุป",
    },
    "en": {
        "app_title": "Lottery History Dashboard",
        "safety_note": "Historical statistical analysis only. This system does not predict or guarantee lottery outcomes.",
        "login": "Login",
        "logout": "Logout",
        "logged_in": "Logged in",
        "username": "Username",
        "password": "Password",
        "missing_login_config": "Missing login config",
        "invalid_login": "Invalid username or password.",
        "language": "Language",
        "settings": "Settings",
        "prediction_method": "Prediction method",
        "rolling_span": "Rolling span",
        "top_n_suggestions": "Top N suggestions",
        "all_prior_rows": "All prior rows",
        "rows": "rows",
        "tab_history": "Lottery History",
        "tab_add": "Add Result",
        "tab_next": "Next Draw Analysis",
        "tab_prediction_history": "Prediction History",
        "tab_accuracy": "Model Accuracy",
        "tab_insights": "AI Insights",
        "tab_status": "System Status",
        "tab_backup": "Backup & Export",
        "tab_model": "Model Comparison",
        "tab_backtest": "Backtest",
        "tab_summary": "Summary",
        "tab_digits": "Digit Frequency",
        "tab_last2": "Top Last2",
        "tab_3digit": "Top 3Digit",
        "history_rows": "History Rows",
        "latest_draw": "Latest Draw",
        "current_method": "Current Method",
        "last_updated": "Last Updated",
        "add_new_result": "Add New Lottery Result",
        "save_result": "Save result",
        "next_draw_analysis": "Next Draw Analysis",
        "source_rows": "Source rows",
        "frequency_last2_top": "Frequency Last2 Top",
        "frequency_3digit_top": "Frequency 3Digit Top",
        "weighted_last2_top": "Weighted Last2 Top",
        "weighted_3digit_top": "Weighted 3Digit Top",
        "hybrid_last2_top": "Hybrid Last2 Top",
        "hybrid_3digit_top": "Hybrid 3Digit Top",
        "digit_position_analysis": "Digit Position Analysis",
        "last2_positions": "last2 positions",
        "three_digit_positions": "3digit positions",
        "hot_cold_numbers": "Hot / Cold Numbers",
        "hot_last2": "Hot last2",
        "hot_3digit": "Hot 3digit",
        "cold_last2": "Cold last2",
        "cold_3digit": "Cold 3digit",
        "method": "method",
        "save_analysis": "Save Analysis",
        "prediction_history": "Prediction History",
        "model_accuracy": "Model Accuracy",
        "total_predictions": "Total Predictions",
        "evaluated": "Evaluated",
        "hit_rate_percent": "Hit Rate %",
        "tracking_file": "Tracking File",
        "accuracy_table": "Accuracy Table",
        "leaderboard_model_ranking": "Leaderboard Model Ranking",
        "hit_rate_comparison": "Hit Rate Comparison",
        "accuracy_trend": "Accuracy Trend",
        "accuracy_refreshed": "Model accuracy refreshed against available actual results.",
        "no_evaluated_predictions": "No evaluated prediction records yet. Save an analysis for a draw date, then add the actual result when available.",
        "ai_insights": "AI Insights",
        "insight_caption": "Insight Layer uses deterministic historical statistical analysis only.",
        "insight_cards": "Insight Cards",
        "average_confidence": "Average Confidence",
        "high_signals": "HIGH Signals",
        "generated": "Generated",
        "warnings": "Warnings",
        "signal_confidence": "Signal / Confidence",
        "warning": "Warning",
        "insight_table": "Insight Table",
        "digit_heatmap": "Digit Heatmap",
        "trend_chart": "Trend Chart",
        "digit_movement_chart": "Digit Movement Chart",
        "insight_history": "Insight History",
        "no_insight_warnings": "No major insight warnings from the current history size and distribution.",
        "system_status": "System Status",
        "best_model": "Best Model",
        "latest_accuracy": "Latest Accuracy",
        "latest_processed_draw": "Latest Processed Draw",
        "system_last_refresh": "System Last Refresh",
        "prediction_records": "Prediction Records",
        "data_quality": "Data Quality",
        "not_evaluated": "Not evaluated",
        "system_ready": "System status is ready. Historical statistical analysis only.",
        "refresh_system_status": "Refresh System Status",
        "current_leaderboard": "Current Leaderboard",
        "latest_process_log": "Latest Process Log",
        "backup_export": "Backup & Export",
        "backup_file_count": "Backup File Count",
        "latest_export_time": "Latest Export Time",
        "storage_usage_estimate": "Storage Usage Estimate",
        "backup_retention": "Backup Retention",
        "latest_backup_table": "Latest Backup Table",
        "latest_count": "Latest",
        "no_backup_center_files": "No Backup Center CSV backups yet.",
        "create_backup": "Create Backup",
        "backup_history": "Backup History",
        "backup_accuracy": "Backup Accuracy",
        "backup_latest_prediction": "Backup Latest Prediction",
        "backup_system_log": "Backup System Log",
        "export": "Export",
        "export_predictions_csv": "Export Predictions CSV",
        "export_accuracy_csv": "Export Accuracy CSV",
        "export_history_csv": "Export History CSV",
        "export_full_system_zip": "Export Full System ZIP",
        "download_latest_export": "Download Latest Export",
        "restore_safety": "Restore Safety",
        "restore_caption": "Restore validates CSV structure before replacing any live file.",
        "no_restore_candidates": "No restore candidates available.",
        "backup_file": "Backup file",
        "restore_target": "Restore target",
        "validate_backup": "Validate Backup",
        "restore_selected_backup": "Restore Selected Backup",
        "backup_valid": "Backup structure is valid for the selected restore target.",
        "model_comparison": "Model Comparison",
        "rolling_accuracy_trend": "Rolling Accuracy Trend",
        "backtest": "Backtest",
        "backtest_note": "Backtest uses only rows before each tested draw.",
        "run_backtest": "Run Backtest",
        "summary": "Summary",
        "recalculate_summary": "Recalculate Summary",
        "digit_frequency": "Digit Frequency",
        "top_last2": "Top 20 Last 2 Digits",
        "top_3digit": "Top 20 Three-Digit Numbers",
        "download": "Download",
        "refresh_completed": "Refresh completed.",
        "refresh_failed": "Refresh failed.",
        "backtest_failed": "Backtest failed.",
        "recalculate_failed": "Recalculate Summary failed.",
        "auto_processing_completed": "Auto processing completed.",
        "auto_processing_failed": "Auto processing failed. Changes were rolled back when possible",
        "analysis_saved_backup": "Analysis saved. Backup created",
        "analysis_saved_tracking": "Analysis saved. Tracking files created.",
        "save_analysis_failed": "Save Analysis failed",
        "backup_created": "Backup created",
        "best_current_model": "Best current model by historical tracking",
        "insight_history_updated": "Insight history updated",
        "new_cards": "new cards",
        "insight_backup_created": "Backup created before insight history overwrite",
        "status_needs_attention": "System status needs attention",
        "refreshing_system": "Refreshing statistics, accuracy, leaderboard, and latest prediction...",
        "manual_backup_success": "Backup created",
        "manual_backup_failed": "Backup failed",
        "export_created": "Export created",
        "export_failed": "Export failed",
        "full_export_created": "Full system export created",
        "full_export_failed": "Full export failed",
        "backup_validation_failed": "Backup validation failed",
        "restore_completed": "Restore completed. Current file was backed up first",
        "restore_blocked": "Restore blocked",
        "running_backtest": "Running backtest...",
        "last_result_file": "Last result file",
        "detail_csv": "Detail CSV",
        "recalculating_summary": "Recalculating summary...",
        "summary_recalculated": "Summary recalculated successfully.",
        "backtest_completed": "Backtest completed",
        "accuracy_leaderboard_refreshed": "Model accuracy and leaderboard refreshed.",
        "prediction_history_refreshed": "Prediction history refreshed.",
        "latest_prediction_generated": "Latest prediction generated.",
        "backtest_model_refreshed": "Backtest and model comparison refreshed.",
        "saved_result_backup": "Saved result. Backup created",
        "missing_data_file": "Missing data file",
        "missing_summary_file": "Missing summary file",
    },
}


def get_text(language: str, key: str) -> str:
    """Return localized UI text with English and key fallback."""
    selected = TEXT.get(language, TEXT[DEFAULT_LANGUAGE])
    return selected.get(key) or TEXT["en"].get(key) or key
